"""best value

Revision ID: 267777b9be7a
Revises: 3e531c2f1234
Create Date: 2024-04-27 12:44:24.122489

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '267777b9be7a'
down_revision = '3e531c2f1234'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('plans', schema=None) as batch_op:
        batch_op.add_column(sa.Column('ai_addon', sa.Boolean(), nullable=False))
        batch_op.add_column(sa.Column('best_value', sa.Boolean(), nullable=False))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('plans', schema=None) as batch_op:
        batch_op.drop_column('best_value')
        batch_op.drop_column('ai_addon')

    # ### end Alembic commands ###
